name: Security Scan - Node.js

on:
    pull_request:
        types: [opened, synchronize, reopened]
    workflow_dispatch:

jobs:
    security-sca:
        name: Snyk SCA Scan
        uses: contentstack/contentstack-ci-workflows/.github/workflows/snyk-sca-scan.yml@main
        secrets: inherit
        with:
            language: "node"
            args: "--all-projects"  # Optional: Scan all projects in monorepo
